apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: springboothelloworld
          image: springboothelloworld:new_version
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
            
---
kind: Service
apiVersion: v1
metadata:
  name: helloworld
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 31380
      targetPort: 8080
  type: NodePort
